administration/urls.py
from django.urls import path
from .views import (
    TaskListView,
    create_ipassport_for_user,
    create_fpassport_for_user,
    restore_ipassport_for_user,
    restore_fpassport_for_user,
    change_address_for_user,
    change_name_for_user,
    change_surname_for_user,
    change_patronymic_for_user
)


urlpatterns = [
    path('tasks/', TaskListView.as_view(), name='tasks_list'),
    path('create-passport/<int:task_pk>/', create_ipassport_for_user, name='create_passport_s'),
    path('create-foreign-passport/<int:task_pk>/', create_fpassport_for_user, name='create_fpassport_s'),
    path('restore-passport/<int:task_pk>/', restore_ipassport_for_user, name='restore_passport_s'),
    path('restore-fpassport/<int:task_pk>/', restore_fpassport_for_user, name='restore_fpassport_s'),
    path('change-address/<int:task_pk>/', change_address_for_user, name='change_address_s'),
    path('change-name/<int:task_pk>/', change_name_for_user, name='change_name_s'),
    path('change-surname/<int:task_pk>/', change_surname_for_user, name='change_surname_s'),
    path('change-patronymic/<int:task_pk>/', change_patronymic_for_user, name='change_patronymic_s'),
]

passport_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('administration.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('passports.urls')),
    path('api/auth/', include('authentication.rest_urls')),
    path('api/my-documents/', include('passports.rest_urls')),
    path('api/staff/', include('administration.rest_urls')),
    path('', include('django_prometheus.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

passports/urls.py
from django.urls import path
from .views import (
    main_page,
    create_passport,
    create_fpassport,
    get_documents,
    restore_passport_loss,
    restore_passport_expiry,
    restore_fpassport_loss,
    restore_fpassport_expiry,
    change_address,
    change_name,
    change_surname,
    change_patronymic
)


urlpatterns = [
    path('', main_page, name='home'),
    path('create-passport/', create_passport, name='create_passport_u'),
    path('create-fpassport/', create_fpassport, name='create_fpassport_u'),
    path('my-documents/', get_documents, name='get_documents'),
    path('restore-passport-loss/', restore_passport_loss, name='restore_passport_loss_u',),
    path('restore-passport-expiry/', restore_passport_expiry, name='restore_passport_expiry_u',),
    path('restore-fpassport-loss/', restore_fpassport_loss, name='restore_fpassport_loss_u',),
    path('restore-fpassport-expiry/', restore_fpassport_expiry, name='restore_fpassport_expiry_u',),
    path('change-address/', change_address, name='change_address_u',),
    path('change-name/', change_name, name='change_name_u',),
    path('change-surname/', change_surname, name='change_surname_u',),
    path('change-patronymic/', change_patronymic, name='change_patronymic_u',),
]

administration/models.py
from django.db import models
from authentication.models import CustomUser


class Task(models.Model):
    STATUS_CHOICES = [
        (0, 'in progress'),
        (1, 'completed'),
        (2, 'rejected')
    ]
    TITLE_CHOICES = [
        ('create an internal passport', 'Створення внутрішнього паспорту'),
        ('create a foreign passport', 'Створення закордонного паспорту'),
        ('create a visa', 'Створення візи'),
        ('extend a visa', 'Подовження візи'),
        ('restore a visa due to loss', 'Відновлення візи'),
        ('restore an internal passport due to loss', 'Відновлення внутрішнього паспорту через втрату'),
        ('restore a foreign passport due to loss', 'Відновлення закордонного паспорту через втрату'),
        ('restore an internal passport due to expiry', 'Відновлення внутрішнього паспорту через закінчення терміну дії'),
        ('restore a foreign passport due to expiry', 'Відновлення закордонного паспорту через закінчення терміну дії'),
        ('change user name', 'Зміна імені користувача'),
        ('change user surname', 'Зміна прізвища користувача'),
        ('change user patronymic', 'Зміна по батькові користувача'),
        ('change registation address', 'Оновлення адреси прописки')
    ]

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(choices=TITLE_CHOICES, max_length=255)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    user_data = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"<Task {self.pk}: `{self.title}`>"

authentication/models.py
from random import randint

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

from passports.models import Address, Passport, ForeignPassport
from passports.utils import COUNTRY_CHOICES
from validation.validate_birth_date import validate_birth_date
from validation.validate_email import validate_email
from validation.validate_record_number import validate_record_number


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser):
    GENDER_CHOICES = [
        ('F', 'Female'),
        ('M', 'Male'),
    ]
    COUNTRY_CHOICES = COUNTRY_CHOICES

    email          = models.EmailField(unique=True, validators=[validate_email,])
    name           = models.CharField(max_length=50)
    surname        = models.CharField(max_length=50)
    patronymic     = models.CharField(max_length=50)
    sex            = models.CharField(max_length=1, choices=GENDER_CHOICES)
    date_of_birth  = models.DateField(validators=[validate_birth_date,])
    place_of_birth = models.CharField(max_length=255)
    nationality    = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    record_number  = models.CharField(max_length=14, unique=True, null=True, validators=[validate_record_number,])

    address          = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    passport         = models.OneToOneField(Passport, on_delete=models.SET_NULL, null=True, related_name='user')
    foreign_passport = models.OneToOneField(ForeignPassport, on_delete=models.SET_NULL, null=True, related_name='user')

    is_active    = models.BooleanField(default=True)
    is_staff     = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD  = 'email'
    EMAIL_FIELD     = 'email'
    REQUIRED_FIELDS = ['name', 'surname', 'patronymic', 'sex', 'date_of_birth', 'place_of_birth', 'nationality']

    def __str__(self):
        return f"{self.name} {self.surname}"

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def save(self, *args, **kwargs):
        if not self.record_number:
            self.record_number = self.date_of_birth.strftime('%Y%m%d') + f'-{randint(1, 99999):05d}'
        super().save(*args, **kwargs)

administration/views.py
import datetime
from random import randint

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView

from .models import Task
from passports.models import Address, Passport, ForeignPassport, Visa
from passports.forms import PassportForm, ForeignPassportForm


class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'
    paginate_by = 5
    template_name = 'administration/task_list.html'
    title_filters = (
        'create-passport',
        'create-foreign-passport',
        # 'create-visa',
        'restore-passport-loss',
        'restore-fpassport-loss',
        'restore-passport-expiry',
        'restore-fpassport-expiry',
        'change-name',
        'change-surname',
        'change-patronymic',
        'change-address',
    )
    title_paths = (
        'create_passport_s',
        'create_fpassport_s',
        # '',
        'restore_passport_s',
        'restore_fpassport_s',
        'restore_passport_s',
        'restore_fpassport_s',
        'change_name_s',
        'change_surname_s',
        'change_patronymic_s',
        'change_address_s'
    )

    def get_queryset(self):
        filters_dict = dict(zip(self.title_filters, Task.TITLE_CHOICES))
        tasks = Task.objects.all().order_by('-created_at', 'status')
        title = self.request.GET.get('title')

        if title and title in self.title_filters:
            tasks = tasks.filter(title=filters_dict[title][0])
        return tasks

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список заявок'
        paths_dict = dict(zip([i[0] for i in Task.TITLE_CHOICES], self.title_paths))
        tasks_with_addresses = []
        for task in context['tasks']:
            task.path = paths_dict[task.title]
            user_data = task.user_data
            if 'address_id' in user_data:
                try:
                    address = Address.objects.get(pk=user_data['address_id'])
                    formatted_address = f"{address.country_code}, {address.region}, {address.settlement}, {address.street}, {address.apartments}, {address.post_code}"
                    user_data['formatted_address'] = formatted_address
                except Address.DoesNotExist:
                    user_data['formatted_address'] = 'Неможливо визначити адресу'
            tasks_with_addresses.append(task)
        context['tasks'] = tasks_with_addresses
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            messages.error(request, 'Дана сторінка недоступна.')
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)


def create_passport(task, model):
    """Creates a new passport (internal or foreign) for the user."""
    today = datetime.date.today()
    ten_years_more = today + datetime.timedelta(days=10 * 365 + 2)
    new_passport = model(
        date_of_issue=today,
        number=randint(10000000, 99999999),
        date_of_expiry=ten_years_more,
        photo=task.user_data['photo'],
    )
    return new_passport


@staff_member_required(login_url='signin')
def create_ipassport_for_user(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status or task.user.passport:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')

    passport = create_passport(task, Passport)
    address = get_object_or_404(Address, pk=task.user_data['address_id'])
    if request.method == 'POST':
        form = PassportForm(request.POST, instance=passport)
        if form.is_valid():
            task.user.passport = form.save()
            task.user.address = address
            task.user.save()
            task.status = 1
            task.save()
            messages.success(request, 'Успішно оформлено внутрішній паспорт!')
            return redirect('tasks_list')
        else:
            messages.error(request, form.errors)
    form = PassportForm(instance=passport)
    context = {
        'form': form,
        'user': task.user,
        'address': address,
        'task': task,
        'title': 'Оформлення паспорту'
    }
    return render(request, 'administration/task_form.html', context=context)


@staff_member_required(login_url='signin')
def create_fpassport_for_user(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status or task.user.foreign_passport:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')

    passport = create_passport(task, ForeignPassport)
    if request.method == 'POST':
        form = ForeignPassportForm(request.POST, instance=passport)
        if form.is_valid():
            task.user.foreign_passport = form.save()
            task.user.save()
            task.status = 1
            task.save()
            messages.success(request, 'Успішно оформлено закордонний паспорт!')
            return redirect('tasks_list')
        else:
            messages.error(request, form.errors)
    form = ForeignPassportForm(instance=passport)
    return render(request, 'administration/task_form.html',
                  {'form': form, 'user': task.user, 'task': task, 'title': 'Оформлення закордонного паспорту'})


@staff_member_required(login_url='signin')
def restore_ipassport_for_user(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')

    new_passport = create_passport(task, Passport)
    if request.method == 'POST':
        form = PassportForm(request.POST, instance=new_passport)
        if form.is_valid():
            task.user.passport.delete()
            task.user.passport = form.save()
            task.user.save()
            task.status = 1
            task.save()
            messages.success(request, 'Успішно поновлено внутрішній паспорт!')
            return redirect('tasks_list')
        else:
            messages.error(request, form.errors)
    form = PassportForm(instance=new_passport)
    return render(request, 'administration/task_form.html',
                  {'form': form, 'user': task.user, 'title': 'Поновлення паспорту',
                   'task': task, 'form_title': 'Встановіть необхідні дані для внутрішнього паспотру:'})


@staff_member_required(login_url='signin')
def restore_fpassport_for_user(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')

    new_passport = create_passport(task, ForeignPassport)
    if request.method == 'POST':
        form = ForeignPassportForm(request.POST, instance=new_passport)
        if form.is_valid():
            visas = Visa.objects.filter(foreign_passport=task.user.foreign_passport)
            visas.delete()
            task.user.foreign_passport.delete()
            task.user.foreign_passport = form.save()
            task.user.save()
            task.status = 1
            task.save()
            messages.success(request, 'Успішно поновлено закордонний паспорт!')
            return redirect('tasks_list')
        else:
            messages.error(request, form.errors)
    form = ForeignPassportForm(instance=new_passport)
    context = {
        'form': form,
        'user': task.user,
        'title': 'Відновлення закордонного паспорту',
        'task': task,
        'form_title': 'Встановіть необхідні дані для відновлення закордонного паспотру користувача:'
    }
    return render(request, 'administration/task_form.html', context=context)


@staff_member_required(login_url='signin')
def change_address_for_user(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')
    addr = get_object_or_404(Address, pk=task.user_data["address_id"])
    if request.method == 'POST':
        task.user.address = addr
        task.user.save()
        task.status = 1
        task.save()
        messages.success(request, 'Успішно поновлено адресу прописки!')
        return redirect('tasks_list')

    return render(request, 'administration/address_form.html',
                  {'user': task.user, 'address': addr, 'title': 'Оновлення адреси прописки'})


def handle_user_field_update(request, task, passport_form, field_name, new_value, fpassport_form=None):
    """Handles updating a specific field on the user object and saving the new passport(s)."""
    if passport_form.is_valid() and (fpassport_form is None or fpassport_form.is_valid()):
        task.user.passport.delete()
        setattr(task.user, field_name, new_value)
        task.user.passport = passport_form.save()

        if fpassport_form:
            Visa.objects.filter(foreign_passport=task.user.foreign_passport).delete()
            task.user.foreign_passport.delete()
            task.user.foreign_passport = fpassport_form.save()

        task.user.save()
        task.status = 1
        task.save()

        messages.success(request, f'Успішно поновлено {field_name} користувача!')
        return redirect('tasks_list')
    else:
        messages.error(request, passport_form.errors)
        if fpassport_form:
            messages.error(request, fpassport_form.errors)


@staff_member_required(login_url='signin')
def change_user_field(request, task_pk, field_name, new_value):
    task = get_object_or_404(Task, pk=task_pk)
    if task.status:
        messages.error(request, 'Заявка від цього користувача вже опрацьована.')
        return redirect('tasks_list')

administration/templates/administration/address_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Внутрішній Паспорт
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <img src="{{ user.passport.photo.url }}"
                            alt="Passport Photo"
                            style="height: 220px; width: 190px;"
                            class="img-fluid mb-4">
                            {% include 'passports/inc/_user_card.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Адреса прописки
                </div>
                <div class="card-body text-center">
                    <div class="row">
                        <div class="col-md-5">
                            <p>
                                <strong>Old Registration Address:</strong><br>
                                {{ user.address.country_code }}, {{ user.address.region }}, {{ user.address.settlement }},
                                {{ user.address.street }}, {{ user.address.apartments }}, {{ user.address.post_code }}
                            </p>
                        </div>
                        <div class="col-md-2 d-flex align-items-center justify-content-center">
                            <i class="fas fa-arrow-right fa-2x"></i>
                        </div>
                        <div class="col-md-5">
                            <p>
                                <strong>New Registration Address:</strong><br>
                                {{ address.country_code }}, {{ address.region }}, {{ address.settlement }},
                                {{ address.street }}, {{ address.apartments }}, {{ address.post_code }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" action="">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark btn-block">Оновити</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

administration/templates/administration/change_name_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Дані користувача:
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                        {% if task.user_data.photo %}
                            <img src="/media/{{ task.user_data.photo }}" 
                            alt="User Photo" 
                            style="height: 220px; width: 190px;"
                            class="img-fluid mb-4">
                        {% else %}
                            <img src="/media/images/images-1.jpg"
                            alt="User Photo" 
                            style="height: 150px; width: 125px;"
                            class="img-fluid mb-4">
                        {% endif %}
                        <p><strong>Authority:</strong> {{ user.passport.authority }}</p>
                        <p><strong>Date of Issue:</strong> {{ user.passport.date_of_issue|date:"d/m/Y" }}</p>
                        <p><strong>Date of Expiry:</strong> {{ user.passport.date_of_expiry|date:"d/m/Y" }}</p>
                        </div>
                        <div class="col-md-7">
                            <p><strong>Surname:</strong> {{ user.surname }}</p>
                            <p><strong>Name:</strong> {{ user.name }}</p>
                            <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                            <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d/m/Y" }}</p>
                            <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                            <p><strong>Sex:</strong> {{ user.sex }}</p>
                            <p><strong>Document Number:</strong> {{ user.passport.number }}</p>
                            <p><strong>Record Number:</strong> {{ user.record_number }}</p>
                            <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                            <p>
                                <strong>Registration Address:</strong><br>
                                {{ user.address.country_code }}, {{ user.address.region }}, {{ user.address.settlement }}, 
                                {{ user.address.street }}, {{ user.address.apartments }}, {{ user.address.post_code }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Відповідні зміни:
                </div>
                <div class="card-body text-center">
                    <div class="row">
                        <div class="col-md-5">
                            {% if field_name == 'name' %}
                                <p><strong>Old Name:</strong> {{ user.name }}</p>
                            {% elif field_name == 'surname' %}
                                <p><strong>Old Surname:</strong> {{ user.surname }}</p>
                                {% elif field_name == 'patronymic' %}
                                <p><strong>Old Patronymic:</strong> {{ user.patronymic }}</p>
                            {% endif %}
                        </div>
                        <div class="col-md-2 d-flex align-items-center justify-content-center">
                            <i class="fas fa-arrow-right fa-2x"></i>
                        </div>
                        <div class="col-md-5">
                            {% if field_name == 'name' %}
                                <p><strong>New Name:</strong> {{ task.user_data.name }}</p>
                            {% elif field_name == 'surname' %}
                                <p><strong>New Surname:</strong> {{ task.user_data.surname }}</p>
                                {% elif field_name == 'patronymic' %}
                                <p><strong>New Patronymic:</strong> {{ task.user_data.patronymic }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">         
            <form method="POST" action="">
                {% csrf_token %}
                <h4 class="text-center mb-2">Встановіть необхідні дані для внутрішнього паспотру:</h4>   
                {{ passport_form.as_p }}

                {% if fpassport_form %}
                <h4 class="text-center mb-2">Встановіть необхідні дані для закордонного паспотру:</h4>   
                {{ fpassport_form.as_p }}
                {% endif %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Зверніть увагу!</strong> 
                    Підтверджуючи цю операцію, вами буде видалено внутрішній та закордонний паспорти 
                    зі старим ім`ям цього користувача та створено нові, з оновленими даними.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

                <button type="submit" class="btn btn-dark btn-block">Підтвердити</button>
            </form>
        </div>
    </div>  
    </div>  
</div>
{% endblock %}

administration/templates/administration/task_list.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <br/>
            <div class="sidebar-sticky">
                <ul class="nav flex-column">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=create-passport">
                            Створення паспорту
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=create-foreign-passport">
                            Створення закордонного паспорту
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=restore-passport-loss">
                            Відновлення внутрішнього паспорту через втрату
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=restore-passport-expiry">
                            Відновлення внутрішнього паспорту через закінчення терміну придатності
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=restore-fpassport-loss">
                            Відновлення закордонного паспорту через втрату
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=restore-fpassport-expiry">
                            Відновлення закордонного паспорту через закінчення терміну придатності
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=change-address">
                            Оновлення адреси прописки
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=change-name">
                            Зміна імені користувача
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=change-surname">
                            Зміна прізвища користувача
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks_list' %}?title=change-patronymic">
                            Зміна по батькові користувача
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Вид послуги</th>
                        <th scope="col">Користувач</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Дата створення</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        <th scope="row">{{ task.id }}</th>
                        <td>{{ task.get_title_display }}</td>
                        <td>
                            <p>{{ task.user }}</p>
                            {% if task.user_data.photo %}
                                <img src="/media/{{ task.user_data.photo }}" alt="" width="100" style="height: 90px; width: 80px;" class="img-fluid">
                            {% elif task.user.passport.photo %}
                            <div class="d-flex align-items-start">
                                <img src="{{ task.user.passport.photo.url }}" alt="" width="100" style="height: 90px; width: 80px;" class="img-fluid">
                            </div>
                            {% endif %}
                        </td>
                        <td>{% if task.status %}
                            <p style="color: green;">завершено</p>
                            {% else %}
                            <p style="color: red;">в процесі</p>
                            {% endif %}
                        </td>
                        <td>{{ task.created_at }}</td>
                        <td>
                            {% if task.status == 0 %}
                            <a href="{% url task.path task.id %}" class="btn btn-info">
                                Оформити
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </div>
</div>
{% endblock %}