passport_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('administration.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('passports.urls')),
    path('api/auth/', include('authentication.rest_urls')),
    path('api/my-documents/', include('passports.rest_urls')),
    path('api/staff/', include('administration.rest_urls')),
    path('', include('django_prometheus.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

passports/urls.py
from django.urls import path
from .views import (
    main_page,
    create_passport,
    create_fpassport,
    get_documents,
    restore_passport_loss,
    restore_passport_expiry,
    restore_fpassport_loss,
    restore_fpassport_expiry,
    change_address,
    change_name,
    change_surname,
    change_patronymic
)


urlpatterns = [
    path('', main_page, name='home'),
    path('create-passport/', create_passport, name='create_passport_u'),
    path('create-fpassport/', create_fpassport, name='create_fpassport_u'),
    path('my-documents/', get_documents, name='get_documents'),
    path('restore-passport-loss/', restore_passport_loss, name='restore_passport_loss_u',),
    path('restore-passport-expiry/', restore_passport_expiry, name='restore_passport_expiry_u',),
    path('restore-fpassport-loss/', restore_fpassport_loss, name='restore_fpassport_loss_u',),
    path('restore-fpassport-expiry/', restore_fpassport_expiry, name='restore_fpassport_expiry_u',),
    path('change-address/', change_address, name='change_address_u',),
    path('change-name/', change_name, name='change_name_u',),
    path('change-surname/', change_surname, name='change_surname_u',),
    path('change-patronymic/', change_patronymic, name='change_patronymic_u',),
]

authentication/models.py
from random import randint

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

from passports.models import Address, Passport, ForeignPassport
from passports.utils import COUNTRY_CHOICES
from validation.validate_birth_date import validate_birth_date
from validation.validate_email import validate_email
from validation.validate_record_number import validate_record_number


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser):
    GENDER_CHOICES = [
        ('F', 'Female'),
        ('M', 'Male'),
    ]
    COUNTRY_CHOICES = COUNTRY_CHOICES

    email          = models.EmailField(unique=True, validators=[validate_email,])
    name           = models.CharField(max_length=50)
    surname        = models.CharField(max_length=50)
    patronymic     = models.CharField(max_length=50)
    sex            = models.CharField(max_length=1, choices=GENDER_CHOICES)
    date_of_birth  = models.DateField(validators=[validate_birth_date,])
    place_of_birth = models.CharField(max_length=255)
    nationality    = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    record_number  = models.CharField(max_length=14, unique=True, null=True, validators=[validate_record_number,])

    address          = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    passport         = models.OneToOneField(Passport, on_delete=models.SET_NULL, null=True, related_name='user')
    foreign_passport = models.OneToOneField(ForeignPassport, on_delete=models.SET_NULL, null=True, related_name='user')

    is_active    = models.BooleanField(default=True)
    is_staff     = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD  = 'email'
    EMAIL_FIELD     = 'email'
    REQUIRED_FIELDS = ['name', 'surname', 'patronymic', 'sex', 'date_of_birth', 'place_of_birth', 'nationality']

    def __str__(self):
        return f"{self.name} {self.surname}"

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def save(self, *args, **kwargs):
        if not self.record_number:
            self.record_number = self.date_of_birth.strftime('%Y%m%d') + f'-{randint(1, 99999):05d}'
        super().save(*args, **kwargs)

passports/models.py
import random
from django.db import models

from validation.validate_authority import validate_authority
from validation.validate_expiry_date import validate_expiry_date
from validation.validate_issue_date import validate_issue_date
from validation.validate_number import validate_number
from validation.validate_post_code import validate_post_code
from .utils import COUNTRY_CHOICES


class Address(models.Model):
    COUNTRY_CHOICES = COUNTRY_CHOICES

    country_code = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    region       = models.CharField(max_length=100)
    settlement   = models.CharField(max_length=100)
    street       = models.CharField(max_length=100)
    apartments   = models.CharField(max_length=10)
    post_code    = models.IntegerField(validators=[validate_post_code,])

    def __str__(self) -> str:
        return f"Address: {self.country_code}, {self.region}, {self.settlement}, {self.street}, {self.apartments}"


class AbstractPassport(models.Model):
    number         = models.IntegerField(primary_key=True, validators=[validate_number,])
    authority      = models.IntegerField(validators=[validate_authority,])
    date_of_issue  = models.DateField(validators=[validate_issue_date])
    date_of_expiry = models.DateField(validators=[validate_expiry_date])
    photo          = models.ImageField(upload_to='photos/passports/%Y/%m/%d/')

    class Meta:
        abstract = True

    def __str__(self):
        return f"Document number: {self.number}"

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = random.randint(10000000, 99999999)
        super().save(*args, **kwargs)


class Passport(AbstractPassport):
    def __str__(self):
        return super().__str__() + "(Internal Passport)"


class ForeignPassport(AbstractPassport):
    def __str__(self):
        return super().__str__() + "(Foreign Passport)"


class Visa(models.Model):
    COUNTRY_CHOICES = COUNTRY_CHOICES

    ENTRY_CHOICES = [
        ('1', 'Single Entry'),
        ('2', 'Double Entry'),
        ('MULT', 'Multiple Entry')
    ]

    TYPE_CHOICES = [
        ('Employment', 'Employment Type'),
        ('Business', 'Business Type'),
        ('Tourist', 'Tourist Type'),
        ('Student', 'Student Type'),
        ('Transit', 'Transit Type'),
    ]

    number           = models.IntegerField(primary_key=True, validators=[validate_number,])

    foreign_passport = models.ForeignKey(ForeignPassport, related_name='visas', on_delete=models.CASCADE)
    place_of_issue   = models.CharField(max_length=50)
    date_of_issue    = models.DateField(validators=[validate_issue_date])
    date_of_expiry   = models.DateField(validators=[validate_expiry_date])
    photo            = models.ImageField(upload_to='photos/visas/%Y/%m/%d/')
    type             = models.CharField(max_length=50, choices=TYPE_CHOICES)
    country          = models.CharField(max_length=2, choices=COUNTRY_CHOICES)
    entry_amount     = models.CharField(max_length=4, choices=ENTRY_CHOICES)
    is_active        = models.BooleanField(default=True)

    def __str__(self):
        return f"Visa to {self.country}. Expiration date: {self.date_of_expiry})"

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = random.randint(10000000, 99999999)
        super().save(*args, **kwargs)

passports/forms.py
from django import forms
from .models import Address, Passport, ForeignPassport


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = '__all__'
        widgets = {
            'country_code': forms.Select(attrs={'class': 'form-control'}),
            'region': forms.TextInput(attrs={'class': 'form-control'}),
            'settlement': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'apartments': forms.TextInput(attrs={'class': 'form-control'}),
            'post_code': forms.NumberInput(attrs={'class': 'form-control'})
        }


class PhotoForm(forms.Form):
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))


class PassportForm(forms.ModelForm):

    class Meta:
        model = Passport
        fields = ('number', 'authority', 'date_of_issue', 'date_of_expiry')
        widgets = {
            'number': forms.NumberInput(attrs={'class': 'form-control'}),
            'authority': forms.NumberInput(attrs={'class': 'form-control'}),
            'date_of_issue': forms.DateInput(attrs={'class': 'form-control'}),
            'date_of_expiry': forms.DateInput(attrs={'class': 'form-control'}),
        }


class ForeignPassportForm(forms.ModelForm):

    class Meta:
        model = ForeignPassport
        fields = ('number', 'authority', 'date_of_issue', 'date_of_expiry')
        widgets = {
            'number': forms.NumberInput(attrs={'class': 'form-control'}),
            'authority': forms.NumberInput(attrs={'class': 'form-control'}),
            'date_of_issue': forms.DateInput(attrs={'class': 'form-control'}),
            'date_of_expiry': forms.DateInput(attrs={'class': 'form-control'}),
        }

passports/templates/passports/address_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<h2 class="text-center mb-4 mt-5">{{ title }}</h2>
<br>

<div class="d-flex justify-content-center">
    <form method="POST" action="" class="w-50" style="max-width: 700px; margin: 0 30px;">
        {% csrf_token %}
        {{ address_form.as_p }}
        <button type="submit" class="btn btn-dark">Оновити</button>
    </form>
</div>
{% endblock %}

passports/templates/passports/create_fpassport.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<h2 class="text-center mb-4 mt-5">{{ title }}</h2>
<br>

<div class="d-flex justify-content-center">
    <form method="POST" action="" class="w-50" style="max-width: 700px; margin: 0 30px;" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Створити</button>
    </form>
</div>
{% endblock %}

passports/templates/passports/create_passport.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        Ваші дані для обробки
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <img id="imgPreview" src="/media/images/images-1.jpg"
                                    class="img-thumbnail rounded-circle"
                                    style="width: 120px; height: 120px; object-fit: cover; cursor: pointer; margin-bottom: 5px;"
                                    alt="User Photo"/>
                                    <input id="id_photo" name="photo" type="file" class="form-control-file" style="display: none;" accept="image/*">
                                </div>
                                {% include './inc/_user_card.html' %}
                            </div>
                        </div>
                    </div>
                </div>
                <h3 class="text-center mb-2">Адреса прописки</h3>
                {{ address_form.as_p }}
                <button type="submit" class="btn btn-dark btn-block">Створити</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
    {% include './inc/_preview_photo.html' %}
{% endblock %}

passports/templates/passports/get_documents.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">Документи</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Внутрішній Паспорт
                </div>
                <div class="card-body">
                    <div class="row">
                        {% if user.passport %}
                            <div class="col-md-5">
                                <img src="{{ user.passport.photo.url }}"
                                style="height: 220px; width: 190px;"
                                alt="Passport Photo"
                                class="img-fluid mb-5">
                                {% include './inc/_user_card.html' %}
                                {% include './inc/_address.html' %}
                            </div>
                        {% else %}
                            <p>У вас ще нема паспорту. <a href="{% url 'create_passport_u' %}">Створити</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    Закордонний Паспорт
                </div>
                <div class="card-body">
                    <div class="row">
                        {% if user.foreign_passport %}
                        <div class="col-md-5">
                            <img src="{{ user.foreign_passport.photo.url }}" alt="Foreign Passport Photo" style="height: 220px; width: 190px;" class="img-fluid mb-5">
                            <p><strong>Authority:</strong> {{ user.foreign_passport.authority }}</p>
                            <p><strong>Date of Issue:</strong> {{ user.foreign_passport.date_of_issue|date:"d/m/Y" }}</p>
                            <p><strong>Date of Expiry:</strong> {{ user.foreign_passport.date_of_expiry|date:"d/m/Y" }}</p>
                        </div>
                        <div class="col-md-7">
                            <p><strong>Surname:</strong> {{ user.surname }}</p>
                            <p><strong>Given Name:</strong> {{ user.name }}</p>
                            <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                            <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d/m/Y" }}</p>
                            <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                            <p><strong>Sex:</strong> {{ user.sex }}</p>
                            <br/>
                            <p><strong>Document Number:</strong> {{ user.foreign_passport.number }}</p>
                            <p><strong>Record Number:</strong> {{ user.record_number }}</p>
                            <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                            <p><strong>Country code:</strong> {{ user.nationality }}</p>
                        </div>
                        {% else %}
                            <p>У вас ще нема закордонного паспорту. <a href="{% url 'create_fpassport_u' %}">Створити</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

passports/templates/passports/index_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-2">
                    <div class="card-header">
                        Ваші дані для обробки
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <img id="imgPreview" src="/media/images/images-1.jpg"
                                    class="img-thumbnail rounded-circle"
                                    style="width: 120px; height: 120px; object-fit: cover; cursor: pointer; margin-bottom: 5px;"
                                    alt="User Photo"/>
                                    <input id="id_photo" name="photo" type="file" class="form-control-file" style="display: none;" accept="image/*">
                                </div>
                                <p><strong>Surname:</strong> {{ user.surname }}</p>
                                <p><strong>Name:</strong> {{ user.name }}</p>
                                <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                            </div>
                            <div class="col-md-7">
                                <p><strong>Sex:</strong> {{ user.sex }}</p>
                                <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d/m/Y" }}</p>
                                <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                                <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                                {% include './inc/_address.html' %}
                            </div>
                        </div>
                    </div>
                </div>
                {% if not create_fpassport %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Зверніть увагу!</strong> Для відновлення відповідного документу ваш минулий документ буде видалено.
                     Якщо це закордонний паспорт, то його буде видалено з усіма візами без автоматичного відновлення.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                <button type="submit" class="btn btn-dark btn-block">Надіслати</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
    {% include './inc/_preview_photo.html' %}
{% endblock %}

passports/templates/passports/update_address.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
<h2 class="text-center mb-4 mt-5">{{ title }}</h2>
<br>
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-header">
                Ваші дані
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        {% if user.passport.photo %}
                            <img src="{{ user.passport.photo.url }}" alt="Passport Photo" class="img-fluid mb-5">
                        {% else %}
                        <img  src="/media/images/images-1.jpg" alt="Passport Photo" style="height: 250px; width: 220px;" class="img-fluid mb-4">
                        {% endif %}
                        <p><strong>Authority:</strong> {{ user.passport.authority }}</p>
                        <p><strong>Date of Issue:</strong> {{ user.passport.date_of_issue|date:"d m Y" }}</p>
                        <p><strong>Date of Expiry:</strong> {{ user.passport.date_of_expiry|date:"d m Y" }}</p>
                    </div>
                    <div class="col-md-7">
                        <p><strong>Surname:</strong> {{ user.surname }}</p>
                        <p><strong>Name:</strong> {{ user.name }}</p>
                        <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                        <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d m Y" }}</p>
                        <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                        <p><strong>Sex:</strong> {{ user.sex }}</p>
                        <p><strong>Document Number:</strong> {{ user.passport.number }}</p>
                        <p><strong>Record Number:</strong> {{ user.record_number }}</p>
                        <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<h3 class="text-center mb-2">Адреса прописки</h3>
<div class="d-flex justify-content-center">
    <form method="POST" action="" class="w-50" style="max-width: 700px; margin: 0 30px;">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Оновити</button>
    </form>
</div>
</div>
{% endblock %}

passports/templates/passports/update_address_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
<h2 class="text-center mb-4 mt-5">{{ title }}</h2>
<br>
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-header">
                Ваші дані
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        {% if user.passport.photo %}
                            <img src="{{ user.passport.photo.url }}" alt="Passport Photo" class="img-fluid mb-5">
                        {% else %}
                        <img  src="/media/images/images-1.jpg" alt="Passport Photo" style="height: 250px; width: 220px;" class="img-fluid mb-4">
                        {% endif %}
                        {% include './inc/_user_card.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<h3 class="text-center mb-2">Адреса прописки</h3>
<div class="d-flex justify-content-center">
    <form method="POST" action="" class="w-50" style="max-width: 700px; margin: 0 30px;">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Оновити</button>
    </form>
</div>
</div>
{% endblock %}

passports/templates/passports/update_data_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        Ваші дані для нового паспорту
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <img id="imgPreview" src="/media/images/images-1.jpg"
                                    class="img-thumbnail rounded-circle"
                                    style="width: 120px; height: 120px; object-fit: cover; cursor: pointer; margin-bottom: 5px;"
                                    alt="User Photo"/>
                                    <input id="id_photo" name="photo" type="file" class="form-control-file" style="display: none;" accept="image/*">
                                </div>
                                <div class="form-group">
                                    {% if user_form.name %}
                                    <p><strong>Name:</strong> {{ user_form.name }}</p>
                                    {% else %}
                                    <p><strong>Name:</strong> {{ user.name }}</p>
                                    {% endif %}
                                    {% if user_form.surname %}
                                    <p><strong>Surname:</strong> {{ user_form.surname }}</p>
                                    {% else %}
                                    <p><strong>Surname:</strong> {{ user.surname }}</p>
                                    {% endif %}
                                    {% if user_form.patronymic %}
                                    <p><strong>Patronymic:</strong> {{ user_form.patronymic }}</p>
                                    {% else %}
                                    <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-md-7">
                                <p><strong>Sex:</strong> {{ user.sex }}</p>
                                <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d/m/Y" }}</p>
                                <br>
                                <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                                <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                                {% include './inc/_address.html' %}
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-dark btn-block">Надіслати</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
    {% include './inc/_preview_photo.html' %}
{% endblock %}

passports/templates/passports/update_name_form.html
{% extends 'base.html' %}

{% block title %}
{{ title }} :: {{ block.super }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4 mt-5">{{ title }}</h2>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        Ваші дані для нового паспорту
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <img id="imgPreview" src="/media/images/images-1.jpg"
                                    class="img-thumbnail rounded-circle" 
                                    style="width: 120px; height: 120px; object-fit: cover; cursor: pointer; margin-bottom: 5px;" 
                                    alt="User Photo"/>
                                    <input id="id_photo" name="photo" type="file" class="form-control-file" style="display: none;" accept="image/*">
                                </div>
                                <div class="form-group">
                                    <p><strong>Name:</strong> {{ user_form.name }}</p>
                                </div>
                                <p><strong>Surname:</strong> {{ user.surname }}</p>
                                <p><strong>Patronymic:</strong> {{ user.patronymic }}</p>
                            </div>
                            <div class="col-md-7">
                                <p><strong>Sex:</strong> {{ user.sex }}</p>
                                <p><strong>Date of Birth:</strong> {{ user.date_of_birth|date:"d/m/Y" }}</p>
                                <br>
                                <p><strong>Place of Birth:</strong> {{ user.place_of_birth }}</p>
                                <p><strong>Nationality:</strong> {{ user.get_nationality_display }}</p>
                                <p>
                                    <strong>Registration Address:</strong><br>
                                    {{ user.address.country_code }}, {{ user.address.region }}, {{ user.address.settlement }}, 
                                    {{ user.address.street }}, {{ user.address.apartments }}, {{ user.address.post_code }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-dark btn-block">Надіслати</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    document.getElementById('imgPreview').onclick = function() {
        document.getElementById('id_photo').click();
    };

    document.getElementById('id_photo').onchange = function(event) {
        const [file] = event.target.files;
        if (file) {
            const imgPreview = document.getElementById('imgPreview');
            imgPreview.src = URL.createObjectURL(file);

            const fileName = file.name;
            document.getElementById('file-chosen').textContent = fileName;
        } else {
            document.getElementById('file-chosen').textContent = 'Файл не обрано';
        }
    };
</script>
{% endblock %}